### ISSUE TITLE
Failed to install 'telerik-imagepicker': CordovaError

### ISSUE THREAD

**Issue by Alwayslazydog** [dhavalsoni2001/ImagePicker#4]
i am sorry about that.
i meet a issue with ionic cordova platform add 
It tell me the plugin is already exists.

`Error during processing of action! Attempting to revert...

Failed to install 'telerik-imagepicker': CordovaError: Uh oh!
"/Users/lx/workspace/moff-client-app/platforms/android/src/com/synconset/ImagePicker.java" already exists!
    at copyNewFile (/Users/lx/workspace/moff-client-app/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Users/lx/workspace/moff-client-app/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/lx/workspace/moff-client-app/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:570:49

(node:11211) UnhandledPromiseRejectionWarning: CordovaError: Uh oh!
"/Users/lx/workspace/moff-client-app/platforms/android/src/com/synconset/ImagePicker.java" already exists!
    at copyNewFile (/Users/lx/workspace/moff-client-app/platforms/android/cordova/lib/pluginHandlers.js:245:45)
    at install (/Users/lx/workspace/moff-client-app/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /Users/lx/workspace/moff-client-app/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/lx/workspace/moff-client-app/platforms/android/cordova/node_modules/q/q.js:570:49
(node:11211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by dhavalsoni2001** [comment]
@Alwayslazydog Is it fixed or still need help?  If it's fixed can you just provide the solution in the comment?
